### ISSUE TITLE
Disable route

### ISSUE THREAD

**Issue by nie7321** [kevincobain2000/laravel-erd#14]
I only want to generate HTML during my build process. I do not want my app to serve the ERD diagram, so it would be nice if I could disable the route.

Right now I sort of can by adding a middleware to deny access -- but that feels like kind of a hack. Maybe setting up the route could be skipped if I change it to null in the config?

**Comment by kevincobain2000** [comment]
How about adding a middleware here

https://github.com/kevincobain2000/laravel-erd/blob/master/config/laravel-erd.php#L7

**Comment by kevincobain2000** [comment]
> Maybe setting up the route could be skipped if I change it to null in the config?

Thanks, yes that could also be done however it is only installed as dev dependency, so your prod builds should not have the route if you do ``composer install --prefer-dist --no-dev``
