### ISSUE TITLE
Collaborate?

### ISSUE THREAD

**Issue by bilogic** [kevincobain2000/laravel-erd#19]
Hi, cool stuff here!

How about basing it off https://github.com/Lt-Mayonesa/wwwsqldesigner or the original https://github.com/ondras/wwwsqldesigner

I managed to turn it into a package already, now working on the relationships, but a little lost. 
This guy here has some incomplete ideas about relationships http://biodesignrealworld.github.io/LaravelDatabaseDesigner/#

What do you think?

**Comment by kevincobain2000** [comment]
Thanks for the invite. wwwsqldesigner looks good. My initial purpose from this lib was the json output, the diagram using gojs came as a bi-product. Feel free to use the [output json](https://github.com/kevincobain2000/laravel-erd#get-json-output) to integrate it with any other diagram tool.
