### ISSUE TITLE
Problem Installing

### ISSUE THREAD

**Issue by Boy19991** [kevincobain2000/laravel-erd#20]
Greetings. 

I am a new programmer. Just wondering if anyone else has a problem with installation. REALLY want to use laravel-erd!

_composer require kevincobain2000/laravel-erd --dev_

 `spatie/laravel-package-tools[1.11.0, ..., 1.11.3] require illuminate/contracts ^7.0|^8.0|^9.0 -> found illuminate/contracts[v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev] but these were not loaded, likely because it conflicts with another require`

   **"require": {**
        "php": "^8.0.18",
        "barryvdh/laravel-debugbar": "^3.5",
        "diglactic/laravel-breadcrumbs": "^6.0",
        "doctrine/dbal": "2.*",
        "fideloper/proxy": "^4.0",
        "google/apiclient": "^2.0",
        "laravel-notification-channels/webpush": "^5.1",
        "laravel/framework": "^6.18.35",
        "laravel/helpers": "^1.4",
        "laravel/tinker": "^2.0",
        "maatwebsite/excel": "^3.1",
        "nesbot/carbon": "^2.41",
        "robicch/jquery-gantt": "^6.3",
        "spatie/laravel-google-calendar": "^3.2"
    },
    **"require-dev": {**
        "facade/ignition": "^1.4",
        "fzaninotto/faker": "^1.9.1",
        "laravel/ui": "^1.0",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^8.0"
    },

Can laravel-erd be used with this setup do you think?

Nick

**Comment by kevincobain2000** [comment]
Thanks, let me have a check-in a few days (soon hopefully).
