### ISSUE TITLE
php artisan erd:generate Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by nguyentranchung** [kevincobain2000/laravel-erd#5]
I get the result when I run this command

**Comment by kevincobain2000** [comment]
Are the rest of artisan commands ok? Such as ``php artisan config:cache``. Sounds like issue with the PHP installation on your machine.

**Comment by jasonhamilton** [comment]
I get the same response.  Other artisan commands work fine.  Is there a way to see the dump file?
