### ISSUE TITLE
Overlapping elements

### ISSUE THREAD

**Issue by stephenjason89** [kevincobain2000/laravel-erd#7]
With a big schema,
There are a lot of overlapping elements. 

![image](https://user-images.githubusercontent.com/3810177/131693501-96714528-e2a1-4d0c-bbdb-a479a98d3561.png)

Thank you for the wonderful package

**Comment by kevincobain2000** [comment]
Hi,
Yes that is one issue. This was the same issue with the https://github.com/beyondcode/laravel-er-diagram-generator.
In which, the produced diagram in beyondcode's is large that needs to be zoomed in and out and trace back the lines and nodes along to identify a connecting.

Therefore, in this package I tried to address that issue by adding 1) check-boxes for the tables 2) check-boxes for relations 3) and interactive to make it usable.

If there are other proposals, to make it user-friendly, I would love to hear feedback.

**Comment by stephenjason89** [comment]
![graph](https://user-images.githubusercontent.com/3810177/131846333-0419132e-4672-489f-8af2-b74420fdc910.png)
I believe they, https://github.com/beyondcode/laravel-er-diagram-generator, may have fixed the issue of overlapping elements. I would much prefer your package though, primarily because it is interactive and easier to read.

To be clear, i am referring to the overlapping tables. In the example above it is the table, receipts, wallets, inventory, sales, etc..

The checkboxes helps a bit on managing the diagram. if i may comment, by default, all tables are shown. Which means, the first action should be uncheck all, not check all. 

I believe, it is already user friendly. Would just be a lot better if the spacing between elements can be fixed and
also relationship with the same table overlaps the table fields, making it hard to read.

I would love to see the line connecting the tables relationships together with the table relationship being highlighted when you hover the mouse on a table.
It would be really easy to follow the lines if that happens.

Overall, this is a great package. Thank you

**Comment by kevincobain2000** [comment]
Thank you for the details. Now I understand about the overlapping issue in details together with your suggestions. 

I will take all the suggestions and see if I can find a way to make it useful. It might take some time but will work on it. 

I ll keep this issue open.

**Comment by stephenjason89** [comment]
Thank you as well. Will be waiting patiently ☺️

**Comment by Thavarajan** [comment]
First of all thanks for this wonder full package, in the mean while is it possible to fetch all the related model for one level when we select a particular model, depends on the selection

**Comment by stephenjason89** [comment]
@kevincobain2000 Is there any update on this?

**Comment by kevincobain2000** [comment]
Sorry no update on this, I haven't been working on this much lately.
I welcome pull reqs tho, will merge em if it fixes your issue.

**Comment by stephenjason89** [comment]
Thanks @kevincobain2000, will try it out once i'm free
